// Generated by CoffeeScript 1.9.2
(function() {
  var About2, SCREEN_HEIGHT, SCREEN_WIDTH, TOPBAR_HEIGHT,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  SCREEN_HEIGHT = 768;

  SCREEN_WIDTH = 1024;

  TOPBAR_HEIGHT = 102 / 2;

  About2 = (function() {
    function About2() {
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      this.animateInCaptionImage = bind(this.animateInCaptionImage, this);
      this.animateInText1Image = bind(this.animateInText1Image, this);
      this.reset = bind(this.reset, this);
      this.view = Ti.UI.createScrollView({
        maxZoomScale: 2.0
      });
      this.view.controller = this;
      this.container = Ti.UI.createView({
        width: SCREEN_WIDTH,
        backgroundColor: "white"
      });
      this.view.add(this.container);
      this.backgroundImage = Ti.UI.createImageView({
        image: "About2-image.png",
        width: 2048 / 2,
        height: 1435 / 2,
        scale: 0.5
      });
      this.container.add(this.backgroundImage);
      this.captionImage = Ti.UI.createImageView({
        image: "About2-Caption.png",
        width: 226 / 2,
        height: 61 / 2,
        scale: 0.5
      });
      this.container.add(this.captionImage);
      this.text1Image = Ti.UI.createImageView({
        image: "About2-Text1.png",
        width: 218 / 2,
        height: 227 / 2,
        scale: 0.5
      });
      this.container.add(this.text1Image);
    }

    About2.prototype.reset = function() {
      this.captionImage.left = -this.captionImage.width;
      this.captionImage.top = 1296 / 2 - TOPBAR_HEIGHT;
      this.text1Image.left = SCREEN_WIDTH + 5;
      return this.text1Image.top = 1134 / 2 - TOPBAR_HEIGHT;
    };

    About2.prototype.animateInText1Image = function() {
      return this.text1Image.animate({
        left: 1685 / 2,
        duration: 200
      });
    };

    About2.prototype.animateInCaptionImage = function() {
      return this.captionImage.animate({
        left: 1406 / 2,
        duration: 200
      }, this.animateInText1Image);
    };

    About2.prototype.init = function() {
      this.reset();
      return this;
    };

    About2.prototype.play = function() {
      this.reset();
      return this.animateInCaptionImage();
    };

    return About2;

  })();

  module.exports = About2;

}).call(this);
