// Generated by CoffeeScript 1.9.2
(function() {
  var About1, SCREEN_HEIGHT, SCREEN_WIDTH,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  SCREEN_WIDTH = 1024;

  SCREEN_HEIGHT = 768;

  About1 = (function() {
    function About1() {
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      this.animateInCaptionImage = bind(this.animateInCaptionImage, this);
      this.animateInText1Image = bind(this.animateInText1Image, this);
      this.animateInText2Image = bind(this.animateInText2Image, this);
      this.reset = bind(this.reset, this);
      this.view = Ti.UI.createScrollView({
        maxZoomScale: 2.0,
        width: Ti.UI.FILL,
        height: Ti.UI.FILL
      });
      this.view.controller = this;
      this.container = Ti.UI.createView({
        width: SCREEN_WIDTH,
        height: 1435 / 2,
        backgroundColor: "white"
      });
      this.view.add(this.container);
      this.backgroundImage = Ti.UI.createImageView({
        image: "About1-image.png",
        width: 2048 / 2,
        height: 1435 / 2,
        scale: 0.5
      });
      this.container.add(this.backgroundImage);
      this.captionImage = Ti.UI.createImageView({
        image: "About1-Caption.png",
        width: 536 / 2,
        height: 74 / 2,
        scale: 0.5
      });
      this.container.add(this.captionImage);
      this.text1Image = Ti.UI.createImageView({
        image: "About1-Text1.png",
        width: 295 / 2,
        height: 148 / 2,
        scale: 0.5
      });
      this.container.add(this.text1Image);
      this.text2Image = Ti.UI.createImageView({
        image: "About1-Text2.png",
        width: 298 / 2,
        height: 127 / 2,
        scale: 0.5
      });
      this.container.add(this.text2Image);
    }

    About1.prototype.reset = function() {
      this.captionImage.left = -this.captionImage.width;
      this.captionImage.top = 440 / 2;
      this.text1Image.left = 371 / 2;
      this.text1Image.top = SCREEN_HEIGHT + this.text1Image.height;
      this.text2Image.left = 371 / 2;
      return this.text2Image.top = SCREEN_HEIGHT + this.text1Image.height;
    };

    About1.prototype.animateInText2Image = function() {
      return this.text2Image.animate({
        top: 877 / 2,
        duration: 200
      });
    };

    About1.prototype.animateInText1Image = function() {
      return this.text1Image.animate({
        top: 671 / 2,
        duration: 200
      }, this.animateInText2Image);
    };

    About1.prototype.animateInCaptionImage = function() {
      return this.captionImage.animate({
        left: 401 / 2,
        duration: 200
      }, this.animateInText1Image);
    };

    About1.prototype.init = function() {
      this.reset();
      return this;
    };

    About1.prototype.play = function() {
      this.reset();
      return this.animateInCaptionImage();
    };

    return About1;

  })();

  module.exports = About1;

}).call(this);
