// Generated by CoffeeScript 1.9.2
(function() {
  var About1, About2, AboutScreen,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  About1 = require("ui/common/About1");

  About2 = require("ui/common/About2");

  AboutScreen = (function() {
    function AboutScreen() {
      this.play = bind(this.play, this);
      this.getCurrentView = bind(this.getCurrentView, this);
      this.init = bind(this.init, this);
      this.onScrollEnd = bind(this.onScrollEnd, this);
      this.view = Ti.UI.createScrollableView();
      this.about1 = new About1().init();
      this.about2 = new About2().init();
      this.view.views = [this.about1.view, this.about2.view];
      this.currentViewIndex = 0;
      this.view.addEventListener("scrollend", this.onScrollEnd);
    }

    AboutScreen.prototype.onScrollEnd = function() {
      if (this.view.currentPage !== this.currentViewIndex) {
        this.currentViewIndex = this.view.currentPage;
        return this.getCurrentView().controller.play();
      }
    };

    AboutScreen.prototype.init = function() {
      return this;
    };

    AboutScreen.prototype.getCurrentView = function() {
      var i, len, ref, v;
      ref = this.view.views;
      for (i = 0, len = ref.length; i < len; i++) {
        v = ref[i];
        v.controller.reset();
      }
      return this.view.views[this.view.currentPage];
    };

    AboutScreen.prototype.play = function() {
      return this.getCurrentView().controller.play();
    };

    return AboutScreen;

  })();

  module.exports = AboutScreen;

}).call(this);
