// Generated by CoffeeScript 1.9.2
(function() {
  var DayViewScreen,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DayViewScreen = (function() {
    function DayViewScreen(image_name, width, height) {
      this.relayout = bind(this.relayout, this);
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      this.view = Ti.UI.createScrollView({
        backgroundColor: "#ede0c8",
        maxZoomScale: 2.0
      });
      this.fullscreenView = Ti.UI.createImageView({
        image: image_name + "-Fullscreen.png",
        width: width / 2,
        height: height / 2,
        left: 0,
        top: 0
      });
      this.view.add(this.fullscreenView);
    }

    DayViewScreen.prototype.init = function() {
      return this;
    };

    DayViewScreen.prototype.play = function() {};

    DayViewScreen.prototype.relayout = function() {};

    return DayViewScreen;

  })();

  module.exports = DayViewScreen;

}).call(this);
