// Generated by CoffeeScript 1.9.2
(function() {
  var FullScreenGallery,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  FullScreenGallery = (function() {
    function FullScreenGallery() {
      this.play = bind(this.play, this);
      this.animateInMainView = bind(this.animateInMainView, this);
      this.setEventData = bind(this.setEventData, this);
      this.reset = bind(this.reset, this);
      this.init = bind(this.init, this);
      this.view = Ti.UI.createImageView({
        image: "Gallery-Image1.png"
      });
      this.view.addEventListener("doubletap", (function(_this) {
        return function() {
          return _this.view.getParent().remove(_this.view);
        };
      })(this));
    }

    FullScreenGallery.prototype.init = function() {
      this.reset();
      return this;
    };

    FullScreenGallery.prototype.reset = function() {};

    FullScreenGallery.prototype.setEventData = function(event_data) {
      this.view.image = "Gallery-Image" + (event_data.current_image_index + 1) + ".png";
      this.view.left = event_data.pos.left;
      this.view.top = event_data.pos.top;
      this.view.width = event_data.width;
      return this.view.height = event_data.height;
    };

    FullScreenGallery.prototype.animateInMainView = function() {
      var anim, m;
      m = Ti.UI.create2DMatrix();
      m = m.scale(2.0);
      anim = Ti.UI.createAnimation({
        transform: m,
        duration: 800
      });
      console.log("scaling view animation...");
      return this.view.animate(anim, (function(_this) {
        return function() {};
      })(this));
    };

    FullScreenGallery.prototype.play = function() {
      return this.animateInMainView();
    };

    return FullScreenGallery;

  })();

  module.exports = FullScreenGallery;

}).call(this);
