// Generated by CoffeeScript 1.9.2
(function() {
  var GalleryScreen,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  GalleryScreen = (function() {
    function GalleryScreen() {
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      this.relayout = bind(this.relayout, this);
      var i, imgInfo, j, thumb_image_wrapper;
      this.view = Ti.UI.createView();
      this.large_scroll_view = Ti.UI.createScrollableView();
      this.images = [];
      this.large_images = [];
      this.thumb_images = [];
      this.thumb_scroll_view = Ti.UI.createScrollView({
        height: 268 / 2,
        contentWidth: "auto",
        contentHeight: "auto"
      });
      for (i = j = 1; j <= 10; i = ++j) {
        imgInfo = {
          large_image: Ti.UI.createImageView({
            image: "Gallery-Image" + i + ".png"
          }),
          thumb_image: Ti.UI.createImageView({
            image: "Gallery-Thumb" + i + ".png",
            width: 223 / 2,
            height: 223 / 2
          })
        };
        this.images.push(imgInfo);
        this.large_images.push(imgInfo.large_image);
        thumb_image_wrapper = Ti.UI.createView({
          width: imgInfo.thumb_image.width + 30,
          height: imgInfo.thumb_image.height + 10,
          left: (i - 1) * (imgInfo.thumb_image.width + 30 / 2),
          top: 0
        });
        thumb_image_wrapper.add(imgInfo.thumb_image);
        this.thumb_scroll_view.add(thumb_image_wrapper);
        this.thumb_images.push(thumb_image_wrapper);
      }
      this.large_scroll_view.views = this.large_images;
      this.thumb_scroll_view.height = this.thumb_images[0].height;
      this.view.add(this.large_scroll_view);
      this.view.add(this.thumb_scroll_view);
      this.large_scroll_view.left = 0;
      this.large_scroll_view.top = 0;
      this.thumb_scroll_view.left = 0;
    }

    GalleryScreen.prototype.relayout = function() {
      this.large_scroll_view.height = this.view.height - this.thumb_scroll_view.height;
      return this.thumb_scroll_view.top = this.large_scroll_view.top + this.large_scroll_view.height;
    };

    GalleryScreen.prototype.init = function() {
      return this;
    };

    GalleryScreen.prototype.play = function() {};

    return GalleryScreen;

  })();

  module.exports = GalleryScreen;

}).call(this);
