// Generated by CoffeeScript 1.9.2
(function() {
  var HighZoneScreen, RoomScreen,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  RoomScreen = require("/ui/common/RoomScreen");

  HighZoneScreen = (function() {
    function HighZoneScreen() {
      this.relayout = bind(this.relayout, this);
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      this.addClickEvent = bind(this.addClickEvent, this);
      this.show3BedroomStudyScreen = bind(this.show3BedroomStudyScreen, this);
      this.show3BedroomScreen = bind(this.show3BedroomScreen, this);
      this.show2BedroomScreen = bind(this.show2BedroomScreen, this);
      this.show1BedroomScreen = bind(this.show1BedroomScreen, this);
      this.assignToCurrentSubscreen = bind(this.assignToCurrentSubscreen, this);
      this.getSubscreenHeight = bind(this.getSubscreenHeight, this);
      this.view = Ti.UI.createView();
      this.toolbarView = Ti.UI.createImageView({
        image: "HighZone-Toolbar.png",
        width: 2048 / 2,
        height: 61 / 2,
        top: 0,
        left: 0
      });
      this.view.add(this.toolbarView);
      this.button1Bedroom = Ti.UI.createButton({
        backgroundImage: "HighZone-Button1Bedroom.png",
        width: 226 / 2,
        height: 61 / 2,
        left: 71 / 2,
        top: 0,
        button_id: 0
      });
      this.toolbarView.add(this.button1Bedroom);
      this.button2Bedroom = Ti.UI.createButton({
        backgroundImage: "HighZone-Button2Bedroom.png",
        width: 226 / 2,
        height: 61 / 2,
        left: 458 / 2,
        top: 0,
        button_id: 1
      });
      this.toolbarView.add(this.button2Bedroom);
      this.button3Bedroom = Ti.UI.createButton({
        backgroundImage: "HighZone-Button3Bedroom.png",
        width: 226 / 2,
        height: 61 / 2,
        left: 845 / 2,
        top: 0,
        button_id: 2
      });
      this.toolbarView.add(this.button3Bedroom);
      this.buttonSplitUnit = Ti.UI.createButton({
        backgroundImage: "HighZone-ButtonSplitUnit.png",
        width: 226 / 2,
        height: 61 / 2,
        left: 1727 / 2,
        top: 0,
        button_id: 3
      });
      this.toolbarView.add(this.buttonSplitUnit);
      this.button3BedroomStudy = Ti.UI.createButton({
        backgroundImage: "HighZone-Button3BedroomStudy.png",
        width: 361 / 2,
        height: 61 / 2,
        left: 1229 / 2,
        top: 0,
        button_id: 4
      });
      this.toolbarView.add(this.button3BedroomStudy);
      this.scrollView = Ti.UI.createScrollableView({
        left: 0,
        top: this.toolbarView.top + this.toolbarView.height
      });
      this.subScreen = null;
      this.onDayViewClicked = null;
    }

    HighZoneScreen.prototype.getSubscreenHeight = function() {
      return this.view.height - this.toolbarView.height;
    };

    HighZoneScreen.prototype.assignToCurrentSubscreen = function(newSubScreen) {
      if (this.subScreen !== null) {
        this.subScreen.view.getParent().remove(this.subScreen.view);
        this.subScreen = null;
      }
      newSubScreen.view.top = this.toolbarView.height;
      newSubScreen.view.height = this.getSubscreenHeight();
      newSubScreen.view.width = this.view.width;
      newSubScreen.relayout();
      newSubScreen.play();
      this.subScreen = newSubScreen;
      this.subScreen.onButtonClicked = this.onDayViewClicked;
      return this.view.add(newSubScreen);
    };

    HighZoneScreen.prototype.show1BedroomScreen = function() {
      var options, roomScreen;
      options = {
        imageInfos: [
          {
            imageName: "HighZone-1Bedroom-QL.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: false
            }
          }, {
            imageName: "HighZone-1Bedroom-QPONML-1.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: false
            }
          }, {
            imageName: "HighZone-1Bedroom-QPONML-2.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: false
            }
          }
        ]
      };
      roomScreen = new RoomScreen(options).init();
      return this.assignToCurrentSubscreen(roomScreen);
    };

    HighZoneScreen.prototype.show2BedroomScreen = function() {
      var options, roomScreen;
      options = {
        imageInfos: [
          {
            imageName: "HighZone-2Bedroom-AJ.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: true
            }
          }, {
            imageName: "HighZone-2Bedroom-CDEFGH-1.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: true
            }
          }, {
            imageName: "HighZone-2Bedroom-CDEFGH-2.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: true
            }
          }, {
            imageName: "HighZone-2Bedroom-AJ.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: true
            }
          }
        ]
      };
      roomScreen = new RoomScreen(options).init();
      return this.assignToCurrentSubscreen(roomScreen);
    };

    HighZoneScreen.prototype.show3BedroomScreen = function() {
      var options, roomScreen;
      options = {
        imageInfos: [
          {
            imageName: "HighZone-3Bedroom-RK.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: false
            }
          }, {
            imageName: "HighZone-3Bedroom-RK-2.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: false
            }
          }, {
            imageName: "HighZone-3Bedroom-RK-3.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: false
            }
          }
        ]
      };
      roomScreen = new RoomScreen(options).init();
      return this.assignToCurrentSubscreen(roomScreen);
    };

    HighZoneScreen.prototype.show3BedroomStudyScreen = function() {
      var options, roomScreen;
      options = {
        imageInfos: [
          {
            imageName: "HighZone-3BedroomStudy-OPNM.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: false
            }
          }, {
            imageName: "HighZone-3BedroomStudy-EF.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: true
            }
          }, {
            imageName: "HighZone-3BedroomStudy-CDGH.png",
            dayViewRow1: {
              type: "ROW1",
              visible: true,
              is_southview: true
            }
          }
        ]
      };
      roomScreen = new RoomScreen(options).init();
      return this.assignToCurrentSubscreen(roomScreen);
    };

    HighZoneScreen.prototype.addClickEvent = function(button) {
      return button.addEventListener("click", (function(_this) {
        return function() {
          if (button.button_id === 0) {
            _this.show1BedroomScreen();
          }
          if (button.button_id === 1) {
            _this.show2BedroomScreen();
          }
          if (button.button_id === 2) {
            _this.show3BedroomScreen();
          }
          if (button.button_id === 4) {
            return _this.show3BedroomStudyScreen();
          }
        };
      })(this));
    };

    HighZoneScreen.prototype.init = function() {
      this.addClickEvent(this.button1Bedroom);
      this.addClickEvent(this.button2Bedroom);
      this.addClickEvent(this.button3Bedroom);
      this.addClickEvent(this.button3BedroomStudy);
      this.addClickEvent(this.buttonSplitUnit);
      return this;
    };

    HighZoneScreen.prototype.play = function() {
      return this.show1BedroomScreen();
    };

    HighZoneScreen.prototype.relayout = function() {
      this.scrollView.top = this.toolbarView.top + this.toolbarView.height;
      this.scrollView.width = this.view.width;
      return this.scrollView.height = this.view.height - this.toolbarView.height;
    };

    return HighZoneScreen;

  })();

  module.exports = HighZoneScreen;

}).call(this);
