// Generated by CoffeeScript 1.9.2
(function() {
  var Intro2,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Intro2 = (function() {
    function Intro2() {
      this.play = bind(this.play, this);
      this.show = bind(this.show, this);
      this.fadeInText1 = bind(this.fadeInText1, this);
      this.fadeInMainView = bind(this.fadeInMainView, this);
      this.fadeOutMainView = bind(this.fadeOutMainView, this);
      this.raiseOnPlayEnds = bind(this.raiseOnPlayEnds, this);
      this.reset = bind(this.reset, this);
      this.view = Ti.UI.createView();
      this.backgroundImage = Ti.UI.createImageView({
        image: 'Intro2-Background.png',
        width: 1024,
        height: 768
      });
      this.view.add(this.backgroundImage);
      this.text1Image = Ti.UI.createImageView({
        image: 'Intro2-Text1.png',
        width: 1327 / 2,
        height: 525 / 2,
        opacity: 0
      });
      this.text1Image.left = this.backgroundImage.width / 2 - this.text1Image.width / 2;
      this.text1Image.top = this.backgroundImage.height / 2 - this.text1Image.height / 2;
      this.view.add(this.text1Image);
      this.onPlayEnds = null;
    }

    Intro2.prototype.reset = function() {
      return this.text1Image.opacity = 0;
    };

    Intro2.prototype.raiseOnPlayEnds = function() {
      if (this.onPlayEnds !== null) {
        return this.onPlayEnds();
      }
    };

    Intro2.prototype.fadeOutMainView = function() {
      return setTimeout((function(_this) {
        return function() {
          return _this.view.animate({
            curve: Ti.UI.ANIMATION_CURVE_EASE_OUT,
            opacity: .0,
            duration: 1000
          }, function() {
            return _this.raiseOnPlayEnds();
          });
        };
      })(this), 3000);
    };

    Intro2.prototype.fadeInMainView = function() {
      return this.view.animate({
        curve: Ti.UI.ANIMATION_CURVE_EASE_OUT,
        opacity: 1.0,
        duration: 2000
      }, (function(_this) {
        return function() {
          return _this.fadeInText1();
        };
      })(this));
    };

    Intro2.prototype.fadeInText1 = function() {
      return this.text1Image.animate({
        curve: Ti.UI.ANIMATION_CURVE_EASE_IN,
        opacity: 1.0,
        duration: 2000
      }, this.fadeOutMainView);
    };

    Intro2.prototype.show = function() {
      this.view.opacity = 1.0;
      return this.view.visible = true;
    };

    Intro2.prototype.play = function() {
      this.reset();
      this.show();
      return this.fadeInMainView();
    };

    return Intro2;

  })();

  module.exports = Intro2;

}).call(this);
