// Generated by CoffeeScript 1.9.2
(function() {
  var Intro1, Intro2, IntroScreen,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Intro1 = require("ui/common/Intro1");

  Intro2 = require("ui/common/Intro2");

  IntroScreen = (function() {
    function IntroScreen() {
      this.play = bind(this.play, this);
      this.onIntro1PlayEnds = bind(this.onIntro1PlayEnds, this);
      this.onIntro2PlayEnds = bind(this.onIntro2PlayEnds, this);
      this.onMainViewClicked = bind(this.onMainViewClicked, this);
      this.raiseOnExit = bind(this.raiseOnExit, this);
      this.view = Ti.UI.createView();
      this.intro1 = new Intro1();
      this.view.add(this.intro1);
      this.intro2 = new Intro2();
      this.view.add(this.intro2);
      this.intro2.view.visible = false;
      this.intro1.onPlayEnds = this.onIntro1PlayEnds;
      this.intro2.onPlayEnds = this.onIntro2PlayEnds;
      this.view.addEventListener("click", this.onMainViewClicked);
      this.onExit = null;
    }

    IntroScreen.prototype.raiseOnExit = function() {
      if (this.onExit !== null) {
        return this.onExit();
      }
    };

    IntroScreen.prototype.onMainViewClicked = function() {
      this.view.getParent().remove(this.view);
      return this.raiseOnExit();
    };

    IntroScreen.prototype.onIntro2PlayEnds = function() {
      this.intro1.view.visible = true;
      this.intro2.view.visible = false;
      return this.intro1.play();
    };

    IntroScreen.prototype.onIntro1PlayEnds = function() {
      console.log("onIntro1PlayEnds called");
      this.intro1.view.visible = false;
      this.intro2.view.visible = true;
      return this.intro2.play();
    };

    IntroScreen.prototype.play = function() {
      return this.intro1.play();
    };

    return IntroScreen;

  })();

  module.exports = IntroScreen;

}).call(this);
