// Generated by CoffeeScript 1.9.2
(function() {
  var Intro1,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Intro1 = (function() {
    function Intro1() {
      this.play = bind(this.play, this);
      this.show = bind(this.show, this);
      this.reset = bind(this.reset, this);
      this.fadeInText1 = bind(this.fadeInText1, this);
      this.fadeInText2 = bind(this.fadeInText2, this);
      this.fadeInMainView = bind(this.fadeInMainView, this);
      this.fadeOutMainView = bind(this.fadeOutMainView, this);
      this.raiseOnPlayEnds = bind(this.raiseOnPlayEnds, this);
      this.view = Ti.UI.createView();
      this.backgroundImage = Ti.UI.createImageView({
        image: 'Intro1-Background.png',
        width: 1024,
        height: 768
      });
      this.view.add(this.backgroundImage);
      this.text1Image = Ti.UI.createImageView({
        image: 'Intro1-Text1.png',
        width: 713 / 2,
        height: 100 / 2,
        left: 329 / 2,
        top: 789 / 2,
        opacity: 0
      });
      this.view.add(this.text1Image);
      this.text2Image = Ti.UI.createImageView({
        image: 'Intro1-Text2.png',
        width: 691 / 2,
        height: 112 / 2,
        left: 1052 / 2,
        top: 678 / 2,
        opacity: 0
      });
      this.view.add(this.text2Image);
      this.onPlayEnds = null;
      this.isFirstStart = true;
    }

    Intro1.prototype.raiseOnPlayEnds = function() {
      console.log("raiseOnPlayEnds called");
      if (this.onPlayEnds !== null) {
        return this.onPlayEnds();
      }
    };

    Intro1.prototype.fadeOutMainView = function() {
      return setTimeout((function(_this) {
        return function() {
          return _this.view.animate({
            curve: Ti.UI.ANIMATION_CURVE_EASE_OUT,
            opacity: .0,
            duration: 1000
          }, function() {
            return _this.raiseOnPlayEnds();
          });
        };
      })(this), 3000);
    };

    Intro1.prototype.fadeInMainView = function() {
      return this.view.animate({
        curve: Ti.UI.ANIMATION_CURVE_EASE_OUT,
        opacity: 1.0,
        duration: 2000
      }, (function(_this) {
        return function() {
          return _this.fadeInText1();
        };
      })(this));
    };

    Intro1.prototype.fadeInText2 = function() {
      return this.text2Image.animate({
        curve: Ti.UI.ANIMATION_CURVE_EASE_IN,
        opacity: 1.0,
        duration: 2000
      }, this.fadeOutMainView);
    };

    Intro1.prototype.fadeInText1 = function() {
      return this.text1Image.animate({
        curve: Ti.UI.ANIMATION_CURVE_EASE_IN,
        opacity: 1.0,
        duration: 2000
      }, this.fadeInText2);
    };

    Intro1.prototype.reset = function() {
      this.text1Image.opacity = 0;
      return this.text2Image.opacity = 0;
    };

    Intro1.prototype.show = function() {
      this.view.opacity = 1.0;
      return this.view.visible = true;
    };

    Intro1.prototype.play = function() {
      this.reset();
      if (this.isFirstStart) {
        this.isFirstStart = false;
        this.show();
        return this.fadeInText1();
      } else {
        return this.fadeInMainView();
      }
    };

    return Intro1;

  })();

  module.exports = Intro1;

}).call(this);
