// Generated by CoffeeScript 1.9.2
(function() {
  var ANIMATION_DURATION, MainMenuScreen, SCREEN_HEIGHT, SCREEN_WIDTH,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ANIMATION_DURATION = 200;

  SCREEN_WIDTH = 1024;

  SCREEN_HEIGHT = 768;

  MainMenuScreen = (function() {
    function MainMenuScreen() {
      this.play = bind(this.play, this);
      this.animateOutSHAndFloorplan = bind(this.animateOutSHAndFloorplan, this);
      this.animateInSHAndFloorplan = bind(this.animateInSHAndFloorplan, this);
      this.animateInLocationAndGallery = bind(this.animateInLocationAndGallery, this);
      this.animateOutLocationAndGallery = bind(this.animateOutLocationAndGallery, this);
      this.menuButtonClicked = bind(this.menuButtonClicked, this);
      this.init = bind(this.init, this);
      this.view = Ti.UI.createView();
      this.buttonSouthHills = Ti.UI.createButton({
        backgroundImage: 'MainMenu-SouthHills.png',
        width: 1025 / 2,
        height: 900 / 2
      });
      this.view.add(this.buttonSouthHills);
      this.buttonGallery = Ti.UI.createButton({
        backgroundImage: 'MainMenu-Gallery.png',
        width: 1025 / 2,
        height: 633 / 2
      });
      this.view.add(this.buttonGallery);
      this.buttonLocation = Ti.UI.createButton({
        backgroundImage: 'MainMenu-Location.png',
        width: 1025 / 2,
        height: 633 / 2
      });
      this.view.add(this.buttonLocation);
      this.buttonFloorplan = Ti.UI.createButton({
        backgroundImage: 'MainMenu-Floorplan.png',
        width: 1025 / 2,
        height: 903 / 2
      });
      this.view.add(this.buttonFloorplan);
      this.onButtonClicked = null;
    }

    MainMenuScreen.prototype.init = function() {
      this.buttonSouthHills.left = 0;
      this.buttonSouthHills.top = -this.buttonSouthHills.height;
      this.buttonSouthHills.addEventListener("click", this.menuButtonClicked);
      this.buttonSouthHills.button_id = 0;
      this.buttonGallery.left = SCREEN_WIDTH + this.buttonGallery.width;
      this.buttonGallery.top = 0;
      this.buttonGallery.addEventListener("click", this.menuButtonClicked);
      this.buttonGallery.button_id = 1;
      this.buttonLocation.left = -this.buttonLocation.width;
      this.buttonLocation.top = this.buttonSouthHills.height;
      this.buttonLocation.addEventListener("click", this.menuButtonClicked);
      this.buttonLocation.button_id = 2;
      this.buttonFloorplan.left = this.buttonSouthHills.width - 1;
      this.buttonFloorplan.top = SCREEN_HEIGHT;
      this.buttonFloorplan.addEventListener("click", this.menuButtonClicked);
      this.buttonFloorplan.button_id = 3;
      return this;
    };

    MainMenuScreen.prototype.menuButtonClicked = function(e) {
      this.animateOutSHAndFloorplan();
      return setTimeout((function(_this) {
        return function() {
          if (_this.onButtonClicked !== null) {
            return _this.onButtonClicked(e.source.button_id);
          }
        };
      })(this), ANIMATION_DURATION * 2);
    };

    MainMenuScreen.prototype.animateOutLocationAndGallery = function() {
      this.buttonLocation.animate({
        left: -this.buttonLocation.width,
        duration: ANIMATION_DURATION
      });
      return this.buttonGallery.animate({
        left: SCREEN_WIDTH + this.buttonGallery.width,
        duration: ANIMATION_DURATION
      });
    };

    MainMenuScreen.prototype.animateInLocationAndGallery = function() {
      this.buttonLocation.animate({
        left: 0,
        duration: ANIMATION_DURATION
      });
      return this.buttonGallery.animate({
        left: this.buttonSouthHills.width - 1,
        duration: ANIMATION_DURATION
      });
    };

    MainMenuScreen.prototype.animateInSHAndFloorplan = function() {
      this.buttonSouthHills.animate({
        top: 1,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {
          return _this.animateInLocationAndGallery();
        };
      })(this));
      return this.buttonFloorplan.animate({
        top: this.buttonGallery.height - 1,
        duration: ANIMATION_DURATION
      });
    };

    MainMenuScreen.prototype.animateOutSHAndFloorplan = function() {
      this.buttonSouthHills.animate({
        top: -this.buttonSouthHills.height,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {
          return _this.animateOutLocationAndGallery();
        };
      })(this));
      return this.buttonFloorplan.animate({
        top: SCREEN_HEIGHT,
        duration: ANIMATION_DURATION
      });
    };

    MainMenuScreen.prototype.play = function() {
      return this.animateInSHAndFloorplan();
    };

    return MainMenuScreen;

  })();

  module.exports = MainMenuScreen;

}).call(this);
