// Generated by CoffeeScript 1.9.2
(function() {
  var NorthViewScreen,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  NorthViewScreen = (function() {
    function NorthViewScreen() {
      this.relayout = bind(this.relayout, this);
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      this.view = Ti.UI.createImageView({
        image: "NorthView-Background.png",
        width: 2048 / 2,
        height: 1296 / 2
      });
      this.buttonNight = Ti.UI.createButton({
        backgroundImage: "NorthView-ButtonNight.png",
        width: 1874 / 2,
        height: 474 / 2,
        left: 92 / 2,
        top: 732 / 2
      });
      this.view.add(this.buttonNight);
      this.buttonDay = Ti.UI.createButton({
        backgroundImage: "NorthView-ButtonDay.png",
        width: 1874 / 2,
        height: 474 / 2,
        left: 92 / 2,
        top: 138 / 2
      });
      this.view.add(this.buttonDay);
    }

    NorthViewScreen.prototype.init = function() {
      return this;
    };

    NorthViewScreen.prototype.play = function() {};

    NorthViewScreen.prototype.relayout = function() {};

    return NorthViewScreen;

  })();

  module.exports = NorthViewScreen;

}).call(this);
