// Generated by CoffeeScript 1.9.2
(function() {
  var RoomViewButton,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  RoomViewButton = (function() {
    function RoomViewButton(options) {
      this.relayout = bind(this.relayout, this);
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      var day_image, night_image;
      this.view = Ti.UI.createView({
        background: "red",
        width: 496 / 2,
        height: 195 / 2
      });
      this.background = Ti.UI.createImageView({
        image: "RoomViewButton-Background.png",
        width: 496 / 2,
        height: 195 / 2,
        left: 0,
        top: 0
      });
      this.view.add(this.background);
      this.is_southview = options.is_southview || false;
      day_image = "RoomViewButton-NorthView-Day.png";
      night_image = "RoomViewButton-NorthView-Night.png";
      if (this.is_southview) {
        day_image = "RoomViewButton-SouthView-Day.png";
        night_image = "RoomViewButton-SouthView-Night.png";
      }
      this.buttonDay = Ti.UI.createButton({
        backgroundImage: day_image,
        width: 226 / 2,
        height: 147 / 2,
        left: 16 / 2,
        top: 31 / 2
      });
      this.view.add(this.buttonDay);
      this.buttonDay = Ti.UI.createButton({
        backgroundImage: night_image,
        width: 226 / 2,
        height: 147 / 2,
        left: 254 / 2,
        top: 31 / 2
      });
      this.view.add(this.buttonDay);
    }

    RoomViewButton.prototype.init = function() {
      return this;
    };

    RoomViewButton.prototype.play = function() {};

    RoomViewButton.prototype.relayout = function() {};

    return RoomViewButton;

  })();

  module.exports = RoomViewButton;

}).call(this);
