// Generated by CoffeeScript 1.9.2
(function() {
  var RoomScreen,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  RoomScreen = (function() {
    function RoomScreen(options) {
      this.relayout = bind(this.relayout, this);
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      var i, imageName, imageView, len, ref, roomView, wrapperScroll;
      this.view = Ti.UI.createView();
      options.dayViewRow1 = options.dayViewRow1 || {};
      options.dayViewRow2 = options.dayViewRow2 || {};
      this.dayViewRow1 = {
        visible: options.dayViewRow1.visible || false,
        is_southview: options.dayViewRow1.is_southview || false
      };
      this.dayViewRow2 = {
        visible: options.dayViewRow2.visible || false,
        is_southview: options.dayViewRow2.is_southview || false
      };
      this.scrollView = Ti.UI.createScrollableView();
      this.view.add(this.scrollView);
      this.imageNames = options.imageNames || [];
      this.roomViews = [];
      ref = this.imageNames;
      for (i = 0, len = ref.length; i < len; i++) {
        imageName = ref[i];
        roomView = Ti.UI.createView();
        wrapperScroll = Ti.UI.createScrollView({
          maxZoomScale: 2.0
        });
        imageView = Ti.UI.createImageView({
          image: imageName,
          width: 2048 / 2,
          height: 1232 / 2
        });
        wrapperScroll.add(imageView);
        roomView.add(wrapperScroll);
        this.roomViews.push(roomView);
      }
      this.scrollView.views = this.roomViews;
    }

    RoomScreen.prototype.init = function() {
      return this;
    };

    RoomScreen.prototype.play = function() {};

    RoomScreen.prototype.relayout = function() {};

    return RoomScreen;

  })();

  module.exports = RoomScreen;

}).call(this);
