// Generated by CoffeeScript 1.9.2
(function() {
  var AboutScreen, GalleryScreen, SCREEN_HEIGHT, ScreenWithTopBarMenu, TopMenuBar,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  TopMenuBar = require("/ui/common/TopMenuBar");

  AboutScreen = require("/ui/common/AboutScreen");

  GalleryScreen = require("/ui/common/GalleryScreen");

  SCREEN_HEIGHT = 768;

  ScreenWithTopBarMenu = (function() {
    function ScreenWithTopBarMenu() {
      this.click = bind(this.click, this);
      this.showGalleryScreen = bind(this.showGalleryScreen, this);
      this.showAboutScreen = bind(this.showAboutScreen, this);
      this.assignToCurrentSubscreen = bind(this.assignToCurrentSubscreen, this);
      this.getSubscreenHeight = bind(this.getSubscreenHeight, this);
      this.play = bind(this.play, this);
      this.animateInTopBar = bind(this.animateInTopBar, this);
      this.init = bind(this.init, this);
      this.view = Ti.UI.createView({
        width: Ti.UI.FILL,
        height: Ti.UI.FILL
      });
      this.topBar = new TopMenuBar().init();
      this.view.add(this.topBar.view);
      this.subScreen = null;
    }

    ScreenWithTopBarMenu.prototype.init = function() {
      this.topBar.view.left = 0;
      this.topBar.view.top = -this.topBar.view.height;
      return this;
    };

    ScreenWithTopBarMenu.prototype.animateInTopBar = function() {
      return this.topBar.view.animate({
        top: 0,
        duration: 500
      });
    };

    ScreenWithTopBarMenu.prototype.play = function() {
      return this.animateInTopBar();
    };

    ScreenWithTopBarMenu.prototype.getSubscreenHeight = function() {
      return SCREEN_HEIGHT - this.topBar.view.height;
    };

    ScreenWithTopBarMenu.prototype.assignToCurrentSubscreen = function(newSubScreen) {
      if (this.subScreen !== null) {
        this.subScreen.view.getParent().remove(this.subScreen.view);
        this.subScreen = null;
      }
      newSubScreen.view.top = this.topBar.view.height;
      newSubScreen.view.height = this.getSubscreenHeight();
      newSubScreen.play();
      this.subScreen = newSubScreen;
      return this.view.add(newSubScreen);
    };

    ScreenWithTopBarMenu.prototype.showAboutScreen = function() {
      var aboutScreen;
      aboutScreen = new AboutScreen().init();
      return this.assignToCurrentSubscreen(aboutScreen);
    };

    ScreenWithTopBarMenu.prototype.showGalleryScreen = function() {
      var galleryScreen;
      galleryScreen = new GalleryScreen().init();
      galleryScreen.view.height = this.getSubscreenHeight();
      galleryScreen.relayout();
      return this.assignToCurrentSubscreen(galleryScreen);
    };

    ScreenWithTopBarMenu.prototype.click = function(button_id) {
      return this.showGalleryScreen();
    };

    return ScreenWithTopBarMenu;

  })();

  module.exports = ScreenWithTopBarMenu;

}).call(this);
