// Generated by CoffeeScript 1.9.2
(function() {
  var AboutScreen, SCREEN_HEIGHT, ScreenWithTopBarMenu, TopMenuBar,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  TopMenuBar = require("ui/common/TopMenuBar");

  AboutScreen = require("ui/common/AboutScreen");

  SCREEN_HEIGHT = 768;

  ScreenWithTopBarMenu = (function() {
    function ScreenWithTopBarMenu() {
      this.click = bind(this.click, this);
      this.play = bind(this.play, this);
      this.animateInTopBar = bind(this.animateInTopBar, this);
      this.init = bind(this.init, this);
      this.view = Ti.UI.createView({
        width: Ti.UI.FILL,
        height: Ti.UI.FILL
      });
      this.topBar = new TopMenuBar().init();
      this.view.add(this.topBar.view);
    }

    ScreenWithTopBarMenu.prototype.init = function() {
      this.topBar.view.left = 0;
      this.topBar.view.top = -this.topBar.view.height;
      return this;
    };

    ScreenWithTopBarMenu.prototype.animateInTopBar = function() {
      return this.topBar.view.animate({
        top: 0,
        duration: 500
      });
    };

    ScreenWithTopBarMenu.prototype.play = function() {
      return this.animateInTopBar();
    };

    ScreenWithTopBarMenu.prototype.click = function(button_id) {
      var aboutScreen;
      aboutScreen = new AboutScreen().init();
      aboutScreen.view.top = this.topBar.view.height;
      aboutScreen.view.height = SCREEN_HEIGHT - this.topBar.view.height;
      this.view.add(aboutScreen);
      return aboutScreen.play();
    };

    return ScreenWithTopBarMenu;

  })();

  module.exports = ScreenWithTopBarMenu;

}).call(this);
