// Generated by CoffeeScript 1.9.2
(function() {
  var SouthViewScreen,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  SouthViewScreen = (function() {
    function SouthViewScreen() {
      this.relayout = bind(this.relayout, this);
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      this.view = Ti.UI.createImageView({
        image: "SouthView-Background.png",
        width: 2048 / 2,
        height: 1296 / 2
      });
      this.buttonNight = Ti.UI.createButton({
        backgroundImage: "SouthView-ButtonNight.png",
        width: 1874 / 2,
        height: 474 / 2,
        left: 92 / 2,
        top: 732 / 2
      });
      this.view.add(this.buttonNight);
      this.buttonDay = Ti.UI.createButton({
        backgroundImage: "SouthView-ButtonDay.png",
        width: 1874 / 2,
        height: 474 / 2,
        left: 92 / 2,
        top: 138 / 2
      });
      this.view.add(this.buttonDay);
    }

    SouthViewScreen.prototype.init = function() {
      return this;
    };

    SouthViewScreen.prototype.play = function() {};

    SouthViewScreen.prototype.relayout = function() {};

    return SouthViewScreen;

  })();

  module.exports = SouthViewScreen;

}).call(this);
