// Generated by CoffeeScript 1.9.2
(function() {
  var TopMenuBar;

  TopMenuBar = (function() {
    function TopMenuBar() {}

    return TopMenuBar;

  })();

  module.exports = TopMenuBar;

}).call(this);
