// Generated by CoffeeScript 1.9.2
(function() {
  var ApplicationWindow, FirstView, MainMenuScreen;

  FirstView = require('ui/common/IntroScreen');

  MainMenuScreen = require("ui/common/MainMenuScreen");

  ApplicationWindow = (function() {
    function ApplicationWindow() {
      var firstView, self;
      self = Ti.UI.createWindow({
        backgroundColor: '#ede0c8',
        orientationModes: [Ti.UI.LANDSCAPE_LEFT, Ti.UI.LANDSCAPE_RIGHT]
      });
      firstView = new FirstView();
      firstView.onExit = (function(_this) {
        return function() {
          var mainMenuScreen;
          mainMenuScreen = new MainMenuScreen().init();
          self.add(mainMenuScreen);
          return mainMenuScreen.play();
        };
      })(this);
      self.add(firstView);
      firstView.play();
      return self;
    }

    return ApplicationWindow;

  })();

  module.exports = ApplicationWindow;

}).call(this);
