// Generated by CoffeeScript 1.9.2
(function() {
  var ApplicationWindow, FirstView, FullScreenGallery, MainMenuScreen, ScreenWithTopBarmenu;

  FirstView = require('ui/common/IntroScreen');

  MainMenuScreen = require("ui/common/MainMenuScreen");

  ScreenWithTopBarmenu = require("ui/common/ScreenWithTopBarMenu");

  FullScreenGallery = require("ui/common/FullScreenGallery");

  ApplicationWindow = (function() {
    function ApplicationWindow() {
      var firstView, self;
      self = Ti.UI.createWindow({
        backgroundColor: '#ede0c8',
        orientationModes: [Ti.UI.LANDSCAPE_LEFT, Ti.UI.LANDSCAPE_RIGHT],
        statusBarStyle: Titanium.UI.iPhone.StatusBar.LIGHT_CONTENT,
        fullscreen: true
      });
      firstView = new FirstView();
      firstView.onExit = (function(_this) {
        return function() {
          var mainMenuScreen;
          mainMenuScreen = new MainMenuScreen().init();
          mainMenuScreen.onButtonClicked = function(button_id) {
            var topBarScreen;
            topBarScreen = new ScreenWithTopBarmenu().init();
            topBarScreen.onDoubleTapped = function(eventInfo) {
              var eventData, fullscreenGallery;
              if (eventInfo.event_type === "GALLERY") {
                eventData = eventInfo.event_data;
                console.log(eventInfo);
                fullscreenGallery = new FullScreenGallery().init();
                fullscreenGallery.setEventData(eventData);
                self.add(fullscreenGallery);
                return fullscreenGallery.play();
              }
            };
            self.add(topBarScreen);
            topBarScreen.play();
            return topBarScreen.click(button_id);
          };
          self.add(mainMenuScreen);
          return mainMenuScreen.play();
        };
      })(this);
      self.add(firstView);
      firstView.play();
      return self;
    }

    return ApplicationWindow;

  })();

  module.exports = ApplicationWindow;

}).call(this);
