// Generated by CoffeeScript 1.9.2
(function() {
  var ApplicationWindow, FirstView, MainMenuScreen, ScreenWithTopBarmenu;

  FirstView = require('ui/common/IntroScreen');

  MainMenuScreen = require("ui/common/MainMenuScreen");

  ScreenWithTopBarmenu = require("ui/common/ScreenWithTopBarmenu");

  ApplicationWindow = (function() {
    function ApplicationWindow() {
      var firstView, self;
      self = Ti.UI.createWindow({
        backgroundColor: '#ede0c8',
        orientationModes: [Ti.UI.LANDSCAPE_LEFT, Ti.UI.LANDSCAPE_RIGHT],
        statusBarStyle: Titanium.UI.iPhone.StatusBar.LIGHT_CONTENT,
        fullscreen: true
      });
      firstView = new FirstView();
      firstView.onExit = (function(_this) {
        return function() {
          var mainMenuScreen;
          mainMenuScreen = new MainMenuScreen().init();
          mainMenuScreen.onButtonClicked = function(button_id) {
            var topBarScreen;
            topBarScreen = new ScreenWithTopBarmenu().init();
            self.add(topBarScreen);
            topBarScreen.play();
            return topBarScreen.click(button_id);
          };
          self.add(mainMenuScreen);
          return mainMenuScreen.play();
        };
      })(this);
      self.add(firstView);
      firstView.play();
      return self;
    }

    return ApplicationWindow;

  })();

  module.exports = ApplicationWindow;

}).call(this);
